### ISSUE TITLE
你好，请问是否可以禁用一下AntDesign相关的Nuget ID？

### ISSUE THREAD

**Issue by ElderJames** [bang88/ant-design-blazor#3]
你好，非常感谢你在早期尝试实现Blazor 版 Ant Design的思路，我们到目前为止投入了很多的精力来完善所有的组件，还受到了微软和蚂蚁官方的注意和推荐。

为了让项目的品牌更显重量，现在决定使用 AntDesign 作为Nuget名。这样可能会跟你之前发布的Nuget包版本冲突，造成用户的困扰。

如果你还希望继续这个项目，我们非常希望你能加入我们团队，一起完成Ant Design的Blazor版本。我们在创造一个开放的社区，非常愿意接受任何好的建议和贡献。

**Comment by BANG88** [comment]
@ElderJames 不好意思，现在才看到。 可以@ 我才会收到通知，可以的。

**Comment by ElderJames** [comment]
@bang88 十分感谢！非常希望你加入我们，一起建设 ant design blazor 的社区。
![image](https://user-images.githubusercontent.com/7550366/84594118-a080d280-ae82-11ea-8d05-a5ea4e4f7312.png)
